export const HttpResponse = {
    SERVER_ERROR: "Internal server error",
    USER_EXIST: "User already exist",
    PAGE_NOT_FOUND: "Route not found",
    USER_NOT_FOUND: "User not found",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    NO_TOKEN: "Token not provided",
    OTP_INCORRECT: "Incorrect otp, try again",
    OTP_NOT_FOUND: "Otp not found",
    INVALID_CREDENTIALS: "Invalid credentials",
    USER_CREATION_FAILED: "User creation failed",
    USER_CREATION_SUCCESS: "User created successfully",
    UNEXPECTED_KEY_FOUND: "Unexpected key found",
    INVALID_EMAIL: "Invalid email address",
    INVALID_PASSWORD: "Invalid  password",
    RESET_PASS_LINK: "Link for resetting password is sended to email",
    TOKEN_EXPIRED: "Token not valid or expired!",
    PASSWORD_CHANGE_SUCCESS: "Password changed successfully!",
    UNAUTHORIZED: "Unauthorized access!",
    PASSWORD_LENGTH: "Your password must be at least 8 characters long",
    PASSWORD_LETTER: "Your password must contain at least one letter",
    PASSWORD_DIGIT: "Your password must contain at least one number",
    PASSWORD_SPECIALCHAR: "Your password must contain at least one special character",
    LOGIN_SUCCESS : "Login successful",
    INVALID_FILE_FORMAT : "File format is not valid",
  };