export const userRoutes = {
    LOGIN : "/login",
    SIGNUP : "/signup",
    OTP : "/otp",
    FORGOT_PASSWORD: "/forgotpassword",
    NEW_PASSWORD: "/newpassword",
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    HOME : "/home",
    LANDING_PAGE : "/",
    ABOUT : '/about',
    CONTACT : '/contact',
    SERVICES : "/services",
    FREELANCER_DASH : "/freelancer-dashboard",
    LOGOUT : "/logout",
}   