export const userRoutes = {
    LOGIN : "/login",
    SIGNUP : "/signup",
    OTP : "/otp",
    FORGOT_PASSWORD: "/forgotpassword",
    NEW_PASSWORD: "/newpassword",
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    HOME : "/home",
    LANDING_PAGE : "/",
    ABOUT : '/about',
    CONTACT : '/contact',
    SERVICES : "/services",
    FREELANCER_DASH : "/freelancer-dashboard",
    Freelancer_Requirements : "/freelancer-requirements",
    COMPLETE_PROFILE : "/complete-profile",
    CREATE_GIG : "/create-gig",
    LISTED_GIG : "/listed-gig",
    LOGOUT : "/logout",
}   